name: Build and Run

on: workflow_dispatch

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build flyfly project
        working-directory: ./FlySpring/flyfly
        run: mvn clean package -P gofly

      - name: Build edgechain-library 
        working-directory: ./edgechain-library
        run: |
          mvn clean package
          cd target
          mvn install:install-file -Dfile=edgechain-lib-1.0.0.jar -DgroupId=com.flyspring -DartifactId=edgechain-lib -Dversion=1.0.0 -Dpackaging=jar

      - name: Build edgechain-app
        working-directory: ./edgechain-app
        run: mvn clean package -DfinalName=edgechain-app-1.0.0

      - name: Upload Script folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Script
          path: ./Script/